name: ProcGuard CI
on:
  push:
    branches:
      - main  # Only trigger on pushes to main
    paths:
      - '**.go'
      - '**.svelte'
      - '**.ts'
      - '**.nix'
      - '**.yml'
      - '**.yaml'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches:
      - main  # Only trigger PRs targeting main
    paths:
      - '**.go'
      - '**.svelte'
      - '**.ts'
      - '**.nix'
      - '**.yml'
      - '**.yaml'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@v15
        with:
          determinate: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Linter
        run: |
          nix develop --command bash -c "cd wails-app && make lint"

      - name: Frontend Format Check
        run: |
          nix develop --command bash -c "cd wails-app/frontend && bun run format-check"
