name: Go CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: Install frontend dependencies
        run: cd gui && npm install
      - name: Run frontend linter
        run: cd gui && npm run lint
      - name: Run frontend formatter check
        run: cd gui && npm run format-check
      - name: Build frontend
        run: make build-frontend
      - name: Run golangci-lint
        env:
          GOOS: windows
        run: |
          echo "Running golangci-lint..."
          golangci-lint run ./...
      - name: Build
        run: make build
