name: ProcGuard CI
on:
  push:
    paths:
      - '**.go'
      - '**.nix'
      - '**.yml'
      - '**.yaml'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths:
      - '**.go'
      - '**.nix'
      - '**.yml'
      - '**.yaml'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@v15
        with:
          determinate: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wails
        run: nix develop --command go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Application
        run: |
          nix develop --command bash -c "cd wails-app && make build"

      - name: Run Linter
        run: |
          nix develop --command bash -c "cd wails-app && make lint"

      - name: Frontend Format Check
        run: |
          nix develop --command bash -c "cd wails-app/frontend && bun run format-check"
